spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?useSSL=false&serverTimezone=UTC
    username: root
    password: jmjtc666
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password: jmjtc666
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090